name: gelir_gider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.3.2
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
